version: '3.8'

services:
  hmi:
    image: yr5-hmi-img:latest
    container_name: hmi
    network_mode: host
    runtime: nvidia

    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/hmi/YR5-HMI:/home/hmi/YR5-HMI
      - /home/hmi/docker/start_and_update.sh:/home/hmi/start_and_update.sh:ro
      # - /home/hmi/Videos:/home/hmi/Videos

    working_dir: /home/hmi
    command: bash /home/hmi/start_and_update.sh
