services:
  gui:
    image: "ubuntu:22.04"
    container_name: "hmi"
    command: "apt update"
    environment:
      - DISPLAY=:0
    volumes:
      - ./:/home/ubuntu
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./setup.sh:./setup.sh
#https://download.qt.io/archive/qt/6.5/6.5.7/src/single/qt-everywhere-opensource-src-6.5.7.tar.xz

